# Generated by Django 4.2.2 on 2023-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_c_registermodel_delete_company_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='addjobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('jobtitle', models.CharField(max_length=20)),
                ('worktype', models.CharField(choices=[('hybrid', 'Hybrid'), ('rural', 'Rural'), ('city', 'City')], max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=20)),
            ],
        ),
    ]
