# Generated by Django 4.2.2 on 2023-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_addjobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('resume', models.ImageField(upload_to='portalapp/static')),
            ],
        ),
    ]
